# permissions for end users to edit robots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robot-editor-role
rules:
- apiGroups:
  - robots.robolaunch.io
  resources:
  - robots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robots.robolaunch.io
  resources:
  - robots/status
  verbs:
  - get
